name: deploy-main-bot

on:
  # push:
  #   branches:
  #     - deploy
  #   paths-ignore:
  #     - scripts/**
  workflow_dispatch:

jobs:
  deploy:
    name: deploy-main-bot
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: curl --fail --location --request POST '${{ secrets.PORTAINER_WEBHOOK_URL }}'
