name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1-12 *'

jobs:
  build:
    name: Command
    runs-on: ubuntu-latest

    steps:
      - name: Checkouk Reposotory
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Submodule
        run: npm run pull
        
      - name: NPM Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- --gh-action
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
